use_frameworks!

platform :ios, '9.0'

target 'RCSceneLog_Example' do
  pod 'RCSceneLog', :path => '../'

  target 'RCSceneLog_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
